Created tests for Tag and Topic
ubyssey/dispatch pull request #527
Opened 2017-05-12 23:59 UTC by seongchanlee

2017-05-16 17:43 UTC, psiemens requested changes
Just a few minor style fixes 😄

2017-05-16 17:43 UTC, psiemens commented on dispatch/tests/test_tags.py
> +
Remove this line break

2017-05-16 17:43 UTC, psiemens commented on dispatch/tests/test_tags.py
> +class tagsTests(DispatchAPITestCase):
Capitalize class names

2017-05-16 17:43 UTC, psiemens commented on dispatch/tests/test_tags.py
> +        Create a dummy tag instance
Format method docstrings on single line:

```py
def _create_tag(self):
  """Create a dummy tag instance"""
```

2017-05-16 17:43 UTC, psiemens commented on dispatch/tests/test_tags.py
> +        """
Fix formatting

2017-05-16 17:43 UTC, psiemens commented on dispatch/tests/test_tags.py
> +        data = {
Change to:
```py
data = {}
```

2017-05-16 17:43 UTC, psiemens commented on dispatch/tests/test_topics.py
> +		"""
Fix formatting

2017-05-16 17:43 UTC, psiemens commented on dispatch/tests/test_topics.py
> +        data = {
Format on single line

2017-05-17 20:13 UTC, seongchanlee commented
Woah what is this massive coverage increase

2017-05-18 18:01 UTC, psiemens approved these changes

2017-05-18 18:05 UTC, merged