584 upcoming event widget
ubyssey/dispatch pull request #586
Opened 2017-06-16 21:33 UTC by Axel-Jacobsen

2017-06-16 21:35 UTC, Axel-Jacobsen commented on dispatch/tests/test_upcoming_event_widget.py
> +            return (datetime.datetime.now() + datetime.timedelta(days=days)).strftime("%B %d, %Y, %I:%M %p").replace('AM', 'a.m.').replace('PM', 'p.m.').replace(" 0", " ")
This line is convoluted, if you have a better solution please write it in!

2017-06-17 19:01 UTC, psiemens requested changes
Looks good overall! Very thoroughly tested 👍

2017-06-17 19:01 UTC, psiemens commented on dispatch/apps/events/models.py
> +    slug = SlugField(max_length=255)
Move this field below `title`

2017-06-17 19:01 UTC, psiemens commented on dispatch/theme/event_widget.py
> +        return data
You can simplify this method:

```py
data['events'] = Event.objects.filter(is_published=True).exclude(pk=data['featured_event']).order_by('start_time')[:5]

return data
```

The event objects can be passed directly to the template -- no need to pick out only the fields you want. This keeps the code simpler and adds for more flexibility if users want to create a custom template.

I didn't think of this earlier, but you'll also want to consider how to handle past events. I think it makes sense to show events that are happening *up to the current day*. So if it's 8pm and an event started at 7pm we'd still show it, but we wouldn't show it the next day. It'd be good to add a test case for this as well.

2017-06-17 19:01 UTC, psiemens commented on dispatch/theme/fields.py
> +                raise InvalidField('Data must be list of integers (i.e. the ids of the models)')
Maybe just "Data must be a list of integer IDs"

2017-06-17 19:01 UTC, psiemens commented on dispatch/tests/test_upcoming_event_widget.py
> +        for index in xrange(5):
If you want to avoid writing `index+1`, you can use `xrange(1,6)`

2017-06-17 19:01 UTC, psiemens commented on dispatch/tests/test_widget_render.py
>          data['events'] = Event.objects.filter(is_published=True).order_by('-start_time')
Change this to `data['events'] = Event.objects.filter(is_published=True)` for simplicity

2017-06-17 19:01 UTC, psiemens commented on dispatch/apps/events/models.py
> +    slug = SlugField(max_length=255)
What happens if you just call `str(datetime.datetime.now() + datetime.timedelta(days=days))`?

2017-06-17 19:49 UTC, Axel-Jacobsen commented on dispatch/apps/events/models.py
> +    slug = SlugField(max_length=255)
You get something like `2017-06-20 12:19:13.111972` - the template language seems to format it differently

2017-06-19 18:14 UTC, psiemens commented on dispatch/tests/test_upcoming_event_widget.py
> +            return (datetime.datetime.now() + datetime.timedelta(days=days)).strftime("%B %d, %Y, %I:%M %p").replace('AM', 'a.m.').replace('PM', 'p.m.').replace(" 0", " ")
What happens if you just call `str(datetime.datetime.now() + datetime.timedelta(days=days)))`?

2017-06-28 17:56 UTC, psiemens approved these changes

2017-06-28 17:57 UTC, merged