589 publish button
ubyssey/dispatch pull request #603
Opened 2017-06-27 21:26 UTC by Axel-Jacobsen

Publish button is working; however, I am getting a bug when I initially click on a new event from `localhost:8000/admin/events`. The first click doesn't redirect to the page, but raises a TypeError (`TypeError: undefined is not an object (evaluating 'props.entities.local[props.listItem.id].is_published'`) and changes the url to `localhost:8000/admin/events/<event id>`. Not sure of the solution, but will find one soon.

2017-06-27 21:58 UTC, joncppl commented
When it's a new item, `props.listItem.id` is null. It throws an error because null is being used as an array index.

I recommend checking whether it's null first. If it *is* null don't render the publish button (or render a dummy, disabled button).

2017-06-28 22:01 UTC, joncppl requested changes
Great work on your first front-end/react issue.

A few things in addition to 
the line comments.

1. publish button is unstyled
You can use the button component from the blueprint framework to make it look consistent
http://blueprintjs.com/docs/#core/components/button

2. Error when you try to publish a new, unsaved event.
Might as well hide it or disable it in this case.

2017-06-28 22:01 UTC, joncppl commented on dispatch/static/manager/src/js/constants/ActionTypes.js
> +export const EVENTS = resourceActionTypes('EVENTS', ['COUNT_PENDING', 'PUBLISH', 'UNPUBLISH'])
`PUBLISH` and `UNPUBLISH` action types aren't used, so they aren't necessary here.

2017-06-28 22:01 UTC, joncppl commented on dispatch/static/manager/src/js/reducers/ToasterReducer.js
> +  case fulfilled(types.EVENTS.PUBLISH):
these publish actions are never fired off, and so these toast messages are never used.

2017-06-29 22:01 UTC, Axel-Jacobsen commented
Did the suggestions from the review by @joncppl, and added a back button to audit page. In terms of the publish button styling, I wrote it as the "PRIMARY" style cause I thought blue would be good. I was also thinking that the success banner should be different? Same colour as publishing 
button, saying "Event Published" or "Event Unpublished". Thoughts?
<img width="392" alt="screen shot 2017-06-29 at 2 49 27 pm" src="https://user-images.githubusercontent.com/20530172/27712412-c0d2f5d2-5cdb-11e7-89d6-2057187da652.png">

2017-06-29 23:34 UTC, merged