Made the 'description' field a textarea
ubyssey/dispatch pull request #638
Opened 2017-07-25 20:15 UTC by Axel-Jacobsen

2017-07-25 22:36 UTC, Axel-Jacobsen commented on dispatch/apps/events/forms.py
> +            'description': Textarea(attrs={'placeholder': 'Description'}),
Takes care of #637

2017-07-28 00:38 UTC, psiemens requested changes

2017-07-28 00:38 UTC, psiemens commented on dispatch/apps/events/forms.py
>  from dispatch.apps.events.models import Event
Add empty line between django and dispatch imports

2017-07-28 00:38 UTC, psiemens commented on dispatch/apps/events/forms.py
> +            'description': Textarea(attrs={'placeholder': 'Description'}),
Nice 👍

2017-07-28 00:39 UTC, psiemens commented
There was just one small change required, so I went ahead and fixed it before merging. Good stuff -- the date validation is something I hadn't thought of

2017-07-28 00:39 UTC, psiemens approved these changes

2017-07-28 00:40 UTC, merged