Added facebook and twitter fields to the person form
ubyssey/dispatch pull request #725
Opened 2017-10-26 05:30 UTC by BenGHolmes

2017-10-26 05:35 UTC, BenGHolmes commented
Just realized I accidentally hard coded something on the front end that will need to be implemented in dispatch. I'll update and commit again tomorrow

2017-10-30 19:18 UTC, psiemens requested changes
Looks solid! Just a few small changes before it's good to go.

2017-10-30 19:18 UTC, psiemens commented on dispatch/migrations/0001_initial.py
> +# -*- coding: utf-8 -*-
Since we haven't been committing migrations files (although we should maybe start), can you remove this file?

2017-10-30 19:18 UTC, psiemens commented on dispatch/static/manager/src/js/api/dispatch.js
> +      console.log(data.values())
Remove `console.log`

2017-10-30 19:39 UTC, psiemens approved these changes

2017-10-30 19:39 UTC, psiemens commented
Feel free to merge once the tests pass 🤘

2017-10-31 16:25 UTC, merged