700 zone search
ubyssey/dispatch pull request #754
Opened 2018-01-10 20:42 UTC by JamieRL

Added search by zone functionality to widget page. Hooked up same as article page etc. Search method is in ThemeManager, passes back to view which handles serialization of objects.

2018-01-10 20:45 UTC, JamieRL commented
Adding tests.

2018-01-12 03:51 UTC, psiemens requested changes
This looks really clean. Nice use of the `ThemeManager`. Just one small fix before merging

2018-01-12 03:51 UTC, psiemens commented on dispatch/static/manager/src/js/pages/Widgets/ZoneIndexPage.js
> +  handleSearchZones(query) {
This method can be taken out -- you can just call `this.props.searchZones` directly

2018-01-12 04:09 UTC, psiemens approved these changes

2018-01-12 04:09 UTC, psiemens commented
Looks good, merge away 👍

2018-01-12 04:10 UTC, merged