841 image modal tags authors
ubyssey/dispatch pull request #847
Opened 2018-08-07 19:56 UTC by Rowansdabomb

2018-08-07 19:57 UTC, Rowansdabomb commented on dispatch/static/manager/src/js/components/modals/ImageManager/index.js
> +    this.props.listImages(this.props.token, this.buildQuery())
remove space

2018-08-07 19:57 UTC, Rowansdabomb commented on dispatch/static/manager/src/js/components/modals/ImageManager/index.js
> +      q: q
refactor

2018-08-07 20:01 UTC, JamieRL requested changes
Just one extra space. Looks good

2018-08-07 20:01 UTC, JamieRL commented on dispatch/static/manager/src/js/components/modals/ImageManager/index.js
> +
extra space

2018-08-08 17:30 UTC, JamieRL approved these changes

2018-08-08 17:39 UTC, merged