Upgrade to Blueprint v3
ubyssey/dispatch pull request #857
Opened 2018-08-20 21:03 UTC by psiemens

- Upgrade Blueprint from v1 to v3
- Improve styling throughout Dispatch admin interface

2018-08-20 21:40 UTC, JamieRL requested changes
Looks great. I really like the UI design. There are a few commented out sections that I'm not sure if we're keeping or not. There's also just 1 typo in the pagetoolbar that's causing errors

2018-08-20 21:40 UTC, JamieRL commented on dispatch/static/manager/src/js/components/Header/Header.js
> +// import { desktopSize } from '../../util/helpers'
Should this still be here?

2018-08-20 21:40 UTC, JamieRL commented on dispatch/static/manager/src/js/components/PageEditor/PageToolbar.js
> +          <li><span className='bp3-breadcrumb bp3-breadcrumb-current'>{props.isNew ? 'New page' : <Text ellipsize={true}>{props.pagep.title}</Text> }</span></li>
typo: `props.pagep.title`

2018-08-20 22:23 UTC, psiemens commented on dispatch/static/manager/src/js/components/PageEditor/PageToolbar.js
> +          <li><span className='bp3-breadcrumb bp3-breadcrumb-current'>{props.isNew ? 'New page' : <Text ellipsize={true}>{props.pagep.title}</Text> }</span></li>
Thanks!

2018-08-21 17:19 UTC, JamieRL approved these changes

2018-08-22 06:42 UTC, merged